### ISSUE TITLE
Test PayPal Pro payment gateway using Sandbox/Dev account

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#138]
Not sure if this will work from inside Docker. If not, I'll wait until Beta-5 to try it on my server.

**Comment by vicos59** [comment]
Just did a fresh install of the current snapshot on my server test domain. PHP 7.4. No issues with install. 

Next I will test the PayPal and PayPal Pro payment gateways and see if image rotation file caching is still an issue in Preview #156 .

**Comment by vicos59** [comment]
![pp pro config fail](https://user-images.githubusercontent.com/6634041/160262228-fb7b8dfd-48d6-436e-890e-76908f29e487.JPG)

I seem to remember that this was reported before and then fixed. Most have been broken in a subsequent commit. I will try to find the relevant Issue and post it here.

**Comment by vicos59** [comment]
Well, it works ok on Docker, but not on my fresh install of the current snapshot on my server using PHP 7.4.

**Comment by vicos59** [comment]
PHP 7.4.

Another problem with the PayPal PRO when trying to submit a paid order (set in testing mode with sandbox creds):

/index.php?a=cart&action=process&main_type=cart&step=payment_choices

```
ParseError: syntax error, unexpected 'clone' (T_CLONE), expecting '(' in /home/xxx/public_html/classes/PEAR/PayPal/SOAP/Client.php(51) : eval()'d code:1
Stack trace:
#0 /home/xxx/public_html/classes/PEAR/PayPal/CallerServices.php(14): require_once()
#1 /home/xxx/public_html/classes/PEAR/PayPal.php(139): include_once('/home/xxx/...')
#2 /home/xxx/public_html/classes/PEAR/PayPal/Profile.php(122): PayPal::getWSDLVersion()
#3 /home/xxx/public_html/classes/PEAR/PayPal/Profile.php(216): Profile->loadEnvironments()
#4 /home/xxx/public_html/classes/PEAR/PayPal/Profile.php(185): Profile->getValidEnvironments()
#5 /home/xxx/public_html/classes/payment_gateways/paypal_pro.php(909): Profile->setEnvironment('sandbox')
#6 /home/xxx/public_html/classes/payment_gateways/paypal_pro.php(617): paypal_proPaymentGateway->_initPaymentProfile()
#7 /home/xxx/public_html/classes/php5_classes/PaymentGateway.class.php(785): paypal_proPaymentGateway::geoCart_payment_choicesProcess(NULL)
#8 /home/xxx/public_html/classes/php5_classes/Cart.class.php(3004): geoPaymentGateway::callUpdate('geoCart_payment...', NULL, 'paypal_pro')
#9 /home/xxx/public_html/classes/php5_classes/Cart.class.php(1720): geoCart->payment_choicesProcess()
#10 /home/xxx/public_html/classes/php5_classes/Cart.class.php(395): geoCart->processStep()
#11 /home/xxx/public_html/index.php(59): geoCart->init()
#12 {main}

```

https://github.com/geodesicsolutions-community/geocore-community/blob/03b6a39b76821863274e4cfdf1ba8e9faf3854e4/src/classes/PEAR/PayPal/SOAP/Client.php#L31-L62

**Comment by vicos59** [comment]
@jonyo, I hate to keep bothering you, but is there any way you could take a look at this? Getting PayPal to work is the last barrier stopping me from getting my upgrade completed. Many thanks.

On a side note, I set up Stripe and it seems to work. If all else fails, this might be an alternate path. My questions are:

- How new is the code. Is it likely to keep working or are they like Facebook where they expect you to update your code every year or so?
- Do you have any implementation notes? For example, I see there is an option to enable ApplePay in Stripe. If I do this, does it automatically work in GeoCore?
