### ISSUE TITLE
Error changing username and password

### ISSUE THREAD

**Issue by ghost** [geodesicsolutions-community/geocore-community#199]
Error: Non-static method geoPC::get_hashed_password() cannot be called statically in /home2/admin/admin_authentication_class.php:474
Stack trace:
#0 /home2/admin_authentication_class.php(519): Admin_auth->update_admin_login(Object(DataAccess), Array)
#1 /home2/admin/php5_classes/Admin.class.php(475): Admin_auth->update_admin_tools_password()
#2 /home2/admin/index.php(16): geoAdmin->load_page()
#3 {main}

**Comment by geosmarty** [comment]
It really depends on the software and php versions you are attempting to use.  PHP 8.0 no longer allows to call non-static class methods with the static call operator, so you need to get an instance of geoPC, i.e; geoPC::getInstance()->get_hashed_password();  Unfortunately this script is not compatible with php8 environments.  There is a commercially maintained php8++ software package coming out soon @ geocoremax.com.  Maybe keep an eye out for that.

**Comment by ghost** [comment]
It really depends on the software and php versions you are attempting to use.  PHP 8.0 no longer allows to call non-static class methods with the static call operator, so you need to get an instance of geoPC::get_hashed_password() .  Unfortunately this script needs more work for php8 environments.
